extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier
plugins:
  - react
  - prettier
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
env:
  browser: true
  es6: true
rules:
  no-console: off
  prettier/prettier:
    - error
    -
      semi: false
      singleQuote: true
overrides:
  files: '**/*.test.js'
  env:
    jest: true
