extends:
  - eslint:recommended
  - plugin:react/recommended
  - standard
  - prettier
  - prettier/standard
plugins:
  - prettier
  - react
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    jsx: true
rules:
  prettier/prettier:
    - error
    -
      semi: false
      singleQuote: true
overrides:
  files: '**/*.test.js'
  env:
    jest: true
